version: '3.3'

services:
  mongodb1:
    image: mongo:5.0.0
    hostname: mongodb1
    container_name: mongodb1
    ports:
      - 27017:27017
    restart: always
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: cfadmin
      MONGO_INITDB_ROOT_PASSWORD: 1q2w3e$R
      MONGO_INITDB_DATABASE: canalframe
    volumes:
      - ./volumes/data/mongo1:/data/db

  mongodb2:
    image: mongo:5.0.0
    hostname: mongodb2
    container_name: mongodb2
    ports:
      - 27018:27017
    restart: always
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: cfadmin
      MONGO_INITDB_ROOT_PASSWORD: 1q2w3e$R
      MONGO_INITDB_DATABASE: canalframe
    volumes:
      - ./volumes/data/mongo2:/data/db

  mongodb3:
    image: mongo:5.0.0
    hostname: mongodb3
    container_name: mongodb3
    ports:
      - 27019:27017
    restart: always
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: cfadmin
      MONGO_INITDB_ROOT_PASSWORD: 1q2w3e$R
      MONGO_INITDB_DATABASE: canalframe
    volumes:
      - ./volumes/data/mongo3:/data/db

networks:
  mongo:
    driver: bridge