version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8989:8080
      - 50000:50000
    environment:
      - JAVA_OPS=-Xmx1g
      - TZ=Asia/Seoul
    restart: always