version: '3'

services:
  mongo1:
    image: mongo:5.0.0
    container_name: mongo1
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    networks:
      - mongo_network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - ./volumes/data/mongo1:/data/db

  mongo2:
    image: mongo:5.0.0
    container_name: mongo2
    expose:
      - 27018
    ports:
      - 27018:27017
    restart: always
    networks:
      - mongo_network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - ./volumes/data/mongo2:/data/db

  mongo3:
    image: mongo:5.0.0
    container_name: mongo3
    expose:
      - 27019
    ports:
      - 27019:27017
    restart: always
    networks:
      - mongo_network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - ./volumes/data/mongo3:/data/db

  mongoku:
    image: huggingface/mongoku:latest
    container_name: mongoku
    ports:
      - 3100:3100
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo_network
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb://mongo1:27017"