version: '3.3'

services:
  mongo1:
    image: mongo:5.0.0
    hostname: mongo1
    container_name: mongo1
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./volumes/data/mongo1:/data/db

  mongo2:
    image: mongo:5.0.0
    hostname: mongo2
    container_name: mongo2
    expose:
      - 27018
    ports:
      - 27018:27017
    restart: always
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./volumes/data/mongo2:/data/db

  mongo3:
    image: mongo:5.0.0
    hostname: mongo3
    container_name: mongo3
    expose:
      - 27019
    ports:
      - 27019:27017
    restart: always
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./volumes/data/mongo3:/data/db

networks:
  mongo:
    driver: bridge