version: '3'

services:
  postgres:
    container_name: postgres16
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cfadm
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: